/* tslint:disable */
/* eslint-disable */

export type ValueTypes = {
    /** The javascript `Date` as string. Type represents date and time as the ISO Date string. */
["DateTime"]:unknown;
	["Entity"]: AliasType<{
	_id?:true,
	Type?:true,
	Fields?:true,
	DateCreated?:true,
	DateUpdated?:true
		__typename?: true
}>;
	["EntityInput"]: {
	Type:number,
	Fields:ValueTypes["JSON"],
	DateCreated:ValueTypes["DateTime"],
	DateUpdated:ValueTypes["DateTime"]
};
	/** The `JSON` scalar type represents JSON values as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf). */
["JSON"]:unknown;
	["Mutation"]: AliasType<{
createEntity?: [{	input:ValueTypes["EntityInput"]},ValueTypes["Entity"]]
		__typename?: true
}>;
	["Query"]: AliasType<{
	entities?:ValueTypes["Entity"],
entitiesByType?: [{	Type:number},ValueTypes["Entity"]]
		__typename?: true
}>
  }

export type PartialObjects = {
    /** The javascript `Date` as string. Type represents date and time as the ISO Date string. */
["DateTime"]:any,
	["Entity"]: {
		__typename?: "Entity";
			_id?:string,
			Type?:number,
			Fields?:PartialObjects["JSON"],
			DateCreated?:PartialObjects["DateTime"],
			DateUpdated?:PartialObjects["DateTime"]
	},
	["EntityInput"]: {
	Type:number,
	Fields:PartialObjects["JSON"],
	DateCreated:PartialObjects["DateTime"],
	DateUpdated:PartialObjects["DateTime"]
},
	/** The `JSON` scalar type represents JSON values as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf). */
["JSON"]:any,
	["Mutation"]: {
		__typename?: "Mutation";
			createEntity?:PartialObjects["Entity"]
	},
	["Query"]: {
		__typename?: "Query";
			entities?:PartialObjects["Entity"][],
			entitiesByType?:PartialObjects["Entity"][]
	}
  }

// -----------------------------------------------

// !!! THIS FILE WAS GENERATED BY TYPE-GRAPHQL !!!

// !!!   DO NOT MODIFY THIS FILE BY YOURSELF   !!!

// -----------------------------------------------

/** The javascript `Date` as string. Type represents date and time as the ISO Date string. */
export type DateTime = any

export type Entity = {
	__typename?: "Entity",
	_id:string,
	Type:number,
	Fields:JSON,
	DateCreated:DateTime,
	DateUpdated:DateTime
}

export type EntityInput = {
		Type:number,
	Fields:JSON,
	DateCreated:DateTime,
	DateUpdated:DateTime
}

/** The `JSON` scalar type represents JSON values as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf). */
export type JSON = any

export type Mutation = {
	__typename?: "Mutation",
	createEntity:Entity
}

export type Query = {
	__typename?: "Query",
	entities:Entity[],
	entitiesByType:Entity[]
}


type Func<P extends any[], R> = (...args: P) => R;
type AnyFunc = Func<any, any>;

type WithTypeNameValue<T> = T & {
  __typename?: true;
};

type AliasType<T> = WithTypeNameValue<T> & {
  __alias?: Record<string, WithTypeNameValue<T>>;
};

type NotUndefined<T> = T extends undefined ? never : T;

export type ResolverType<F> = NotUndefined<F extends [infer ARGS, any] ? ARGS : undefined>;

export type ArgsType<F extends AnyFunc> = F extends Func<infer P, any> ? P : never;

interface GraphQLResponse {
  data?: Record<string, any>;
  errors?: Array<{
    message: string;
  }>;
}
export type MapInterface<SRC, DST> = SRC extends {
  __interface: infer INTERFACE;
  __resolve: infer IMPLEMENTORS;
}
  ? ObjectToUnion<
      Omit<
        {
          [Key in keyof Omit<DST, keyof INTERFACE | '__typename'>]: Key extends keyof IMPLEMENTORS
            ? MapType<IMPLEMENTORS[Key], DST[Key]> &
                Omit<
                  {
                    [Key in keyof Omit<
                      DST,
                      keyof IMPLEMENTORS | '__typename'
                    >]: Key extends keyof INTERFACE
                      ? LastMapTypeSRCResolver<INTERFACE[Key], DST[Key]>
                      : never;
                  },
                  keyof IMPLEMENTORS
                > &
                (DST extends { __typename: any }
                  ? MapType<IMPLEMENTORS[Key], { __typename: true }>
                  : {})
            : never;
        },
        keyof INTERFACE | '__typename'
      >
    >
  : never;

export type ValueToUnion<T> = T extends {
  __typename: infer R;
}
  ? {
      [P in keyof Omit<T, '__typename'>]: T[P] & {
        __typename: R;
      };
    }
  : T;

export type ObjectToUnion<T> = {
  [P in keyof T]: T[P];
}[keyof T];

type Anify<T> = { [P in keyof T]?: any };


type LastMapTypeSRCResolver<SRC, DST> = SRC extends undefined
  ? undefined
  : SRC extends Array<infer AR>
  ? LastMapTypeSRCResolver<AR, DST>[]
  : SRC extends { __interface: any; __resolve: any }
  ? MapInterface<SRC, DST>
  : SRC extends { __union: any; __resolve: infer RESOLVE }
  ? ObjectToUnion<MapType<RESOLVE, ValueToUnion<DST>>>
  : DST extends boolean
  ? SRC
  : MapType<SRC, DST>;

type MapType<SRC extends Anify<DST>, DST> = DST extends boolean
  ? SRC
  : DST extends {
      __alias: any;
    }
  ? {
      [A in keyof DST["__alias"]]: Required<SRC> extends Anify<
        DST["__alias"][A]
      >
        ? MapType<Required<SRC>, DST["__alias"][A]>
        : never;
    } &
      {
        [Key in keyof Omit<DST, "__alias">]: DST[Key] extends [
          any,
          infer PAYLOAD
        ]
          ? LastMapTypeSRCResolver<SRC[Key], PAYLOAD>
          : LastMapTypeSRCResolver<SRC[Key], DST[Key]>;
      }
  : {
      [Key in keyof DST]: DST[Key] extends [any, infer PAYLOAD]
        ? LastMapTypeSRCResolver<SRC[Key], PAYLOAD>
        : LastMapTypeSRCResolver<SRC[Key], DST[Key]>;
    };

type OperationToGraphQL<V, T> = <Z extends V>(o: Z | V, variables?: Record<string, any>) => Promise<MapType<T, Z>>;

type CastToGraphQL<V, T> = (
  resultOfYourQuery: any
) => <Z extends V>(o: Z | V) => MapType<T, Z>;

type fetchOptions = ArgsType<typeof fetch>;

export type SelectionFunction<V> = <T>(t: T | V) => T;
type FetchFunction = (query: string, variables?: Record<string, any>) => any;


export declare function Thunder(
  fn: FetchFunction
):{
  query: OperationToGraphQL<ValueTypes["Query"],Query>,mutation: OperationToGraphQL<ValueTypes["Mutation"],Mutation>
}

export declare function Chain(
  ...options: fetchOptions
):{
  query: OperationToGraphQL<ValueTypes["Query"],Query>,mutation: OperationToGraphQL<ValueTypes["Mutation"],Mutation>
}

export declare const Zeus: {
  query: (o: ValueTypes["Query"]) => string,mutation: (o: ValueTypes["Mutation"]) => string
}

export declare const Cast: {
  query: CastToGraphQL<
  ValueTypes["Query"],
  Query
>,mutation: CastToGraphQL<
  ValueTypes["Mutation"],
  Mutation
>
}

export declare const Selectors: {
  query: SelectionFunction<ValueTypes["Query"]>,mutation: SelectionFunction<ValueTypes["Mutation"]>
}


export declare const Gql: ReturnType<typeof Chain>
